version: '3.8'

services:
  conferences-fe:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: conferences-fe
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
    volumes:
      - .:/app # Montar todo el código dentro del contenedor
      - /app/node_modules # Evita sobrescribir los node_modules del contenedor
    restart: unless-stopped
    command: ["yarn", "dev", "--host"]
